services:
  # Frontend (Static Site)
  - type: web
    name: portfoliomahidhar-frontend
    env: static
    plan: free
    buildCommand: |
      echo "Building frontend..."
      cd frontend
      npm ci --only=production
      npm run build
      echo "Frontend build complete"
      ls -la dist/
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend (Node.js API)
  - type: web
    name: portfoliomahidhar-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false