services:
  # Frontend (Web Service for Static Files)
  - type: web
    name: portfoliomahidhar-frontend
    env: node
    plan: free
    buildCommand: |
      echo "Building frontend..."
      cd frontend
      npm ci
      npm run build
      echo "Frontend build complete"
      ls -la dist/
      echo "Checking _redirects file..."
      cat public/_redirects
      cd ..
    startCommand: |
      cd frontend
      npm install -g serve
      serve -s dist -l $PORT
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false

  # Backend (Node.js API)
  - type: web
    name: portfoliomahidhar-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false