services:
  # Frontend (Web Service for Static Files)
  - type: web
    name: portfoliomahidhar-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm run build && cd .. && npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false

  # Backend (Node.js API)
  - type: web
    name: portfoliomahidhar-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
